### ISSUE TITLE
ModuleNotFoundError: No module named 'csv_parser'

### ISSUE THREAD

**Issue by appletonwebb** [thelehhman/CSV-Mapper#10]
Using Python 3.6.3 (Mac OS):

```
>>> import csvmapper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/csvmapper/__init__.py", line 9, in <module>
    from csv_parser import CSVParser, CSVWriter
ModuleNotFoundError: No module named 'csv_parser'
```

(Installed with pip)

**Comment by thelehhman** [comment]
Python 3 is not currently supported fully.

**Comment by appletonwebb** [comment]
Thank you for clarifying @thelehhman.
